# FROM nvidia/cuda:11.2.1-cudnn8-devel-ubuntu20.04
FROM nvidia/cuda:11.0.3-cudnn8-devel-ubuntu20.04

RUN apt update && apt install -y \
        python3.8 \
        python3-pip \
        wget \
        git \
        libopenexr-dev \
        git-lfs && \
    apt clean

RUN rm /usr/bin/python3 && \
    ln -s /usr/bin/python3.8 /usr/bin/python3 && \
    ln -s /usr/bin/python3.8 /usr/bin/python

RUN python3 -m pip install --upgrade pip

# install requirements
COPY requirements.txt /env/requirements.txt
RUN python3 -m pip install --no-cache-dir -r /env/requirements.txt


# GitHub installations:
RUN python3 -m pip install git+https://github.com/zhennongchen/CTProjector.git

# c3d 
# RUN useradd -m -p c3dpwd -g sudo c3duser
# RUN wget 'https://sourceforge.net/projects/c3d/files/c3d/Nightly/c3d-nightly-Linux-gcc64.tar.gz'
# RUN tar -xf c3d-nightly-Linux-gcc64.tar.gz
# RUN pwd
# RUN cp -a /c3d-1.4.0-Linux-gcc64/bin/. /usr/local/bin

COPY entrypoint.sh /env/entrypoint.sh
RUN chmod +x /env/entrypoint.sh

COPY compile.sh /env/compile.sh
RUN chmod +x /env/compile.sh

ENTRYPOINT [ "/env/entrypoint.sh" ]